version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/prisma
    env_file:
      - .env
    environment:
      - NODE_ENV=production

volumes:
  sqlite_data: